### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by Suburbanno** [galac-tech/HE-hacked-database-helper#11]
"No script running"
on Tampermonkey

http://prntscr.com/bh77lb

**Comment by 0x2bad** [comment]
If you followed the [steps](https://github.com/galac-tech/HE-hacked-database-helper/wiki/Instructions#installation) correctly then the plugin should be working.

The reason why it is saying `No Script Running` is because **you are on the wrong URL**.

Try going to your **hacked database** and see if it is working.

If you are still encountering any problems then please join us on [Discord](https://discord.gg/014Qsli1cOatwCBj4).
